server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://liceotrujillo.c7ggk8k46269.us-east-2.rds.amazonaws.com:3306/liceotrujillo_db
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update #create-drop
    show-sql: true

appDescription: "Liceo Trujillo API"
appVersion: "1.0.0"

#swagger http://localhost:8080/swagger-ui/index.html
springdoc:
  swagger-ui:
    path: /index.html
logging:
  level:
    org.springframework.security.web.*: debug