server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/liceotrujillo
    username: root
    password: 948900930
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

appDescription: "Liceo Trujillo API"
appVersion: "1.0.0"

#swagger http://localhost:8080/swagger-ui/index.html
springdoc:
  swagger-ui:
    path: /index.html